"""
explanation.py — ConstructAI AI Explanation Generator
======================================================
Produces human-readable explanations of the optimizer's
decision process for the "Why AI Chose This Plan" panel.
"""

import random


def generate_explanation(disruption: dict, optimized_result: dict) -> dict:
    """
    Generate a structured AI explanation with:
    - disruption analysis
    - recalculated constraints
    - optimization reasoning
    - action items taken
    """
    opt = optimized_result["optimized_plan"]
    base_name = optimized_result["best_base"]
    scores = optimized_result["scores"]
    improvements = optimized_result["improvements"]

    # Contextual strategies based on disruption type
    strategies = {
        "rain_delay": [
            "Shifted exposed-activity schedules to covered work zones",
            "Activated weather-resistant curing protocols for concrete",
            "Rerouted crane paths to minimize wind-exposure risk",
            "Deployed temporary weather shields on critical sections",
        ],
        "worker_shortage": [
            "Redistributed tasks across available crews using skill-matching",
            "Activated cross-training protocols for multi-skilled workers",
            "Engaged standby subcontractor agreements for critical trades",
            "Prioritized critical-path activities to minimize float erosion",
        ],
        "material_delay": [
            "Sourced alternate supplier from regional backup network",
            "Resequenced non-dependent activities to fill wait periods",
            "Substituted approved alternative materials where possible",
            "Negotiated expedited shipping for high-priority deliveries",
        ],
        "equipment_breakdown": [
            "Deployed backup equipment from satellite yard",
            "Restructured lift sequences to use available crane capacity",
            "Switched to manual hoist for lightweight materials temporarily",
            "Scheduled emergency mobile crane rental for heavy lifts",
        ],
    }

    disruption_id = disruption.get("id", "rain_delay")
    selected_strategies = strategies.get(disruption_id, strategies["rain_delay"])
    random.shuffle(selected_strategies)
    used_strategies = selected_strategies[:3]

    # Build explanation object
    explanation = {
        "disruption_analysis": {
            "event": disruption["name"],
            "severity": disruption["severity"],
            "impact_summary": disruption["description"],
            "time_impact": f"+{round((disruption['time_impact'] - 1) * 100)}% duration increase",
            "cost_impact": f"+{round((disruption['cost_impact'] - 1) * 100)}% cost increase",
        },
        "recalculated_constraints": {
            "description": (
                f"The digital twin re-evaluated all {len(scores)} candidate plans "
                f"using a weighted composite scoring model. Each plan was scored on "
                f"time-efficiency (50%), cost-efficiency (30%), and risk-resilience (20%)."
            ),
            "plan_scores": {name: score for name, score in scores.items()},
            "selected_base": base_name,
        },
        "optimization_reasoning": {
            "description": (
                f"{base_name} was selected as the optimal recovery base due to its "
                f"superior composite resilience score. The AI optimizer then applied "
                f"adaptive re-scheduling to further improve the plan."
            ),
            "strategies_applied": used_strategies,
        },
        "result_summary": {
            "final_duration": f"{opt['duration_days']} days",
            "final_cost": f"${opt['cost']:,.0f}",
            "final_risk": f"{opt['risk_score']}/100",
            "duration_improvement": f"{improvements['duration_reduction']}%",
            "cost_improvement": f"{improvements['cost_savings']}%",
            "risk_improvement": f"{improvements['risk_reduction']}%",
        },
        "ai_note": (
            "This optimization was generated by ConstructAI's adaptive simulation engine. "
            "The digital twin continuously evaluates site telemetry against the execution "
            "model to find recovery paths that minimize project deviation."
        ),
    }

    return explanation
